### ISSUE TITLE
Update configuration samples. 

### ISSUE THREAD

**Issue by gisochre** [exonum/exonum-doc#103]
https://github.com/exonum/exonum-doc/blob/master/src/architecture/configuration.md#sample-configuration-file

replace with link? 
https://github.com/exonum/exonum/blob/master/exonum/tests/testdata/config/config02.toml

**Comment by slowli** [comment]
This is a more broad problem that is associated with reflecting exonum/exonum#62 in documentation.

**Comment by gisochre** [comment]
This is a broader problem of propagating/pipelining changes in code to doc.

**Comment by slowli** [comment]
But this particular issue is about a quite specific problem with documentation, right? 🙂 As for elaborating the general workflow, #27 is (rightfully) open, so if you have suggestions, you may write them there.
