### ISSUE TITLE
Website: Some Major-Minor Issues

### ISSUE THREAD

**Issue by lazaridiscom** [exonum/exonum-doc#166]
[moved here from: exonum/exonum#435]

(Note: I'm a **veteran** to IT (software & electronics), and a **newcomer** to the blockchain domain)

This is a collection of issues. It addresses essentially the C-level (as in Cxx like CEO, CTO etc.).

* The product website (exonum.com) is **primarily** a marketing-instrument
* The website (exonum.com) should **prominently** mention strengths.
* Category: Exonum is a framework for the creation of **private** blockchains.
* Strength: Exonum has real-life government-level Success Stories
* Exonum is backed by a commercial entity (bitfury.com)

See, you may think "everyone in the blockchain business domain knows Bitfury". Newcomers do not, and if an evaluator has to fight through the masses of frameworks and tools, he may oversee that a quite impressive company is behind the exonum project.

### Support

For me (in the role of an evaluator who has to pick a blockchain-toolset), those are some of the relevant requirements:

* Exonum source-code is available 100% under a liberal open-source-license.
* The project is really open, it encourages contributions from different folks
* Commercial support is available (Question: does bitfury provide commercial support? )
* Missing: a clear pointer to the commercial entity which support the project.

### Menu

Current Menu: 

EXONUM - FRAMEWORK - USE CASES - PARTNERS - RESOURCES - CONTACT US

* "Framework" **could** be renamed to "Product"
* "USE CASES" could be renamed to "Quick Start" (Demos should be made available in sourc-code, enabling a very fast project-start.
* "PARTNERS" could be renamed to "SUCCESS STORIES", where exonum shows his real-life success
* RESOURCES could be renamed to "PROJECT", separating clearly the projec-related stuff. Should contain a TEAM submenu
* CONTACT US should contain some basic contact-info (instead of a direct email-link)

Suggested Menu:

EXONUM - PRODUCT - DEMOS - STORIES - PROJECT - CONTACT

alternatively: DEMO = "QUICK STARTS", STORIES =>"SUCCESS STORIES"

It is important that the landing-page shows immediately the most relevant "product classifications" (e.g.: private blockchain), the most impressive success story, and the easiest quick-start (get a system up and running in under an hour, including source-code etc.).

Ideally, the landing-page would mention the commercial backup (Bitfury). An indirect decent way to do so is to mention "Commercial Grade Support" available (which is an absolute plus for an open-source project).

### Mockup

All this above can trigger "a discussion till the death". It has sometimes less effort to create a "mockup" and show suggestions than to discuss them. This would be simplified by making the website sources available (see: exonum/exonum-doc#163)

**Comment by slowli** [comment]
Sorry, but this issue is not relevant to this repository for pretty much the same reasons it is not relevant to the `exonum` repository. This repository concerns Exonum documentation, while the issue is about the the structure of Exonum website. The Exonum website is not covered and will not be covered by repositories in the `exonum` organization, at least in the short term. You can (and are welcome to) submit your feedback about the website through available public (gitter, reddit) or private (email) channels.

**Comment by lazaridiscom** [comment]
> the issue is about the the structure of Exonum website.

Its about far(!) more things, but I'll not elaborate, as my evaluation ends here.

You can (and are welcome to) use the feedback and forward it to the relevant people, or you can 100% ignore it.

At this point, I'm out.
