### ISSUE TITLE
Update docs to actual state of framework and correct some critical moments.

### ISSUE THREAD

**Issue by BarexaS** [exonum/exonum-doc#193]
In docs (https://exonum.com/doc/architecture/serialization/) explanation about field **Payload length** is incorrect. At ligth client we can see that it's represent the size of whole transaction (including headers, body and signature). So it's calculated as 74 + body size of tranaction.

Plus, all examples are old, and cannot be used with exonum 0.6

**Comment by dmitry-timofeev** [comment]
Seems to have been resolved quite some time ago, thanks for reporting.
